# Generated by Django 3.0.6 on 2020-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('date_re', models.DateField()),
                ('degree', models.IntegerField()),
                ('department', models.CharField(max_length=10)),
            ],
        ),
    ]
